name: MushroomJump
main: me.FieldZ.MushroomJump.MushroomJump
authors: [FieldZ, Devil Boy]
version: 1.4
description: Players can jump from mushroom to mushroom! Very nice!

permissions:
    MushroomJump.affected:
        default: true
        description: Will be affected by mushroom-jumping.